### ISSUE TITLE
Documenting Packages

### ISSUE THREAD

**Issue by f-allian** [christopher-wild/FAIR4RS-Packaging#4]
1. Documenting Packages

    - Why document? (tie it in with FAIR4RS principles; findability, etc)
    - Documenting functions with `roxygen2`
    - Using vignettes for, e.g., tutorials
    - [Diataxis](https://diataxis.fr/) framework for software docs

**Comment by christopher-wild** [comment]
Will be hard to not overlap with `4. Documentation - Joe Heffer`. He covers both documenting the software i.e. docstrings, and documentation around the software like licensing, DOIs, versions, etc.
